/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthForm: typeof import('./components/Forms/AuthForm/AuthForm.vue')['default']
    BaseButton: typeof import('./components/Base/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/Base/BaseIcon.vue')['default']
    BottomBar: typeof import('./components/Navigation/BottomBar/BottomBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NewJobForm: typeof import('./components/Forms/NewJobForm/NewJobForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/Navigation/TopBar/TopBar.vue')['default']
  }
}
